"""
FHIR Bundle Assembler — Explanation Agent
Collects all FHIR resources generated by upstream agents into a single R4 Bundle.

Resources collected:
  - Condition        ← Diagnosis Agent (fhir_conditions list)
  - DiagnosticReport ← Imaging Triage Agent (fhir_diagnostic_report)
  - MedicationRequest← Drug Safety Agent (fhir_medication_requests list)
  - CarePlan         ← Digital Twin Agent (fhir_care_plan)
"""
import uuid
from datetime import datetime, timezone
from typing import Optional


AI_BUNDLE_DISCLAIMER = (
    "This FHIR Bundle was generated by MediTwin AI, a multi-agent clinical decision support system. "
    "All resources are AI-generated provisional outputs. "
    "Physician review and validation required before clinical use."
)


def build_fhir_bundle(
    patient_id: str,
    diagnosis_output: Optional[dict],
    imaging_output: Optional[dict],
    drug_safety_output: Optional[dict],
    digital_twin_output: Optional[dict],
) -> dict:
    """
    Assemble a FHIR R4 Bundle (type: collection) from all agent outputs.
    Gracefully handles missing/None agent outputs.

    Returns:
        FHIR Bundle dict
    """
    entries = []

    # ── Conditions from Diagnosis Agent ───────────────────────────────────────
    if diagnosis_output:
        fhir_conditions = diagnosis_output.get("fhir_conditions", [])
        for condition in fhir_conditions:
            if condition and condition.get("resourceType") == "Condition":
                entries.append({
                    "fullUrl": f"urn:uuid:{uuid.uuid4()}",
                    "resource": condition,
                })

        # If fhir_conditions not present, build a minimal one from top diagnosis
        if not fhir_conditions and diagnosis_output.get("top_icd10_code"):
            icd = diagnosis_output.get("top_icd10_code", "")
            display = diagnosis_output.get("top_diagnosis", "")
            entries.append({
                "fullUrl": f"urn:uuid:{uuid.uuid4()}",
                "resource": {
                    "resourceType": "Condition",
                    "subject": {"reference": f"Patient/{patient_id}"},
                    "code": {
                        "coding": [{
                            "system": "http://hl7.org/fhir/sid/icd-10",
                            "code": icd,
                            "display": display,
                        }]
                    },
                    "verificationStatus": {
                        "coding": [{"code": "provisional"}]
                    },
                    "clinicalStatus": {
                        "coding": [{"code": "active"}]
                    },
                    "note": [{"text": f"AI-generated provisional diagnosis. Confidence: {diagnosis_output.get('differential_diagnosis', [{}])[0].get('confidence', 0):.0%}"}],
                },
            })

    # ── DiagnosticReport from Imaging Triage Agent ────────────────────────────
    if imaging_output and not imaging_output.get("mock", False):
        fhir_report = imaging_output.get("fhir_diagnostic_report")
        if fhir_report and fhir_report.get("resourceType") == "DiagnosticReport":
            entries.append({
                "fullUrl": f"urn:uuid:{uuid.uuid4()}",
                "resource": fhir_report,
            })

    # ── MedicationRequests from Drug Safety Agent ─────────────────────────────
    if drug_safety_output:
        med_requests = drug_safety_output.get("fhir_medication_requests", [])
        for med_req in med_requests:
            if med_req and med_req.get("resourceType") == "MedicationRequest":
                entries.append({
                    "fullUrl": f"urn:uuid:{uuid.uuid4()}",
                    "resource": med_req,
                })

    # ── CarePlan from Digital Twin Agent ──────────────────────────────────────
    if digital_twin_output and not digital_twin_output.get("mock", False):
        care_plan = digital_twin_output.get("fhir_care_plan")
        if care_plan and care_plan.get("resourceType") == "CarePlan":
            entries.append({
                "fullUrl": f"urn:uuid:{uuid.uuid4()}",
                "resource": care_plan,
            })

    # ── Assemble Bundle ───────────────────────────────────────────────────────
    bundle = {
        "resourceType": "Bundle",
        "id": str(uuid.uuid4()),
        "type": "collection",
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "meta": {
            "tag": [{
                "system": "http://meditwin.ai/fhir/tags",
                "code": "ai-generated",
                "display": "AI-Generated Clinical Decision Support",
            }]
        },
        "entry": entries,
        "note": [{"text": AI_BUNDLE_DISCLAIMER}],
        "_entry_count": len(entries),
        "_resource_types": list({
            e["resource"]["resourceType"]
            for e in entries
            if "resource" in e and "resourceType" in e["resource"]
        }),
    }

    return bundle