"""
SOAP Note Generator — Explanation Agent
Generates a structured clinical SOAP note from all agent outputs.

Uses: LLM with clinical terminology prompt
Separate from patient_writer.py — different tone, vocabulary, output format.
Medical disclaimer always appended as a template string (never LLM-dependent).
"""
import os
from typing import Optional

from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import JsonOutputParser

MEDICAL_DISCLAIMER = (
    "\n\nAI-GENERATED CLINICAL DECISION SUPPORT — NOT A SUBSTITUTE FOR PHYSICIAN JUDGMENT. "
    "All findings, diagnoses, and recommendations require physician review and verification "
    "before clinical action. This output was generated by MediTwin AI and has not been "
    "validated by a licensed clinician for this specific patient encounter."
)

SOAP_SYSTEM = """You are a clinical documentation specialist generating a structured SOAP note.
Use standard clinical terminology. Be concise and precise.
Return ONLY valid JSON. No preamble, no markdown.
"""

SOAP_USER = """Generate a clinical SOAP note from the following data.

PATIENT DATA:
Age/Gender: {age}y {gender}
Chief complaint: {chief_complaint}
Active conditions: {conditions}
Current medications: {medications}
Allergies: {allergies}

DIAGNOSTIC FINDINGS:
Final diagnosis: {final_diagnosis} (confidence: {confidence:.0%})
Abnormal labs: {abnormal_labs}
Imaging: {imaging_summary}
Drug safety: {drug_safety_summary}

TREATMENT RECOMMENDATION:
{treatment_recommendation}

RISK SCORES (Digital Twin):
Baseline mortality risk (30d): {mortality_risk:.0%}
30-day readmission risk: {readmission_risk:.0%}

Return JSON with these exact keys:
{{
  "subjective": "Patient history, chief complaint, symptoms in 2-3 sentences",
  "objective": "Vital findings, abnormal labs with values, imaging results, relevant medications",
  "assessment": "Primary diagnosis with confidence, supporting evidence, drug safety alerts, risk profile",
  "plan": ["Action item 1", "Action item 2", "...up to 8 items"],
  "clinical_summary_one_liner": "One-line clinical summary for handoff"
}}

Use clinical abbreviations where appropriate (CAP, WBC, CRP, INR, IV, PO, etc.).
Return ONLY JSON."""


def generate_soap_note(
    patient_state: dict,
    consensus_output: dict,
    lab_output: Optional[dict],
    imaging_output: Optional[dict],
    drug_safety_output: Optional[dict],
    digital_twin_output: Optional[dict],
    chief_complaint: str = "Not specified",
) -> dict:
    """
    Generate a SOAP note via LLM.
    Falls back to a rule-based template if LLM unavailable.
    Medical disclaimer is always appended to assessment field.
    """
    api_key = os.getenv("GOOGLE_API_KEY")

    # Build context strings
    demo = patient_state.get("demographics", {})
    age = demo.get("age", "?")
    gender = demo.get("gender", "unknown")

    conditions = ", ".join(
        c.get("display", "") for c in patient_state.get("active_conditions", [])
    ) or "None documented"

    medications = ", ".join(
        f"{m.get('drug', '')} {m.get('dose', '')}".strip()
        for m in patient_state.get("medications", [])
    ) or "None"

    allergies = ", ".join(
        f"{a.get('substance', '')} ({a.get('reaction', '')})"
        for a in patient_state.get("allergies", [])
    ) or "NKDA"

    abnormal_labs = ", ".join(
        f"{l.get('display', '')}: {l.get('value', '')} {l.get('unit', '')} [{l.get('flag', '')}]"
        for l in patient_state.get("lab_results", [])
        if l.get("flag") in ("HIGH", "LOW", "CRITICAL")
    ) or "None"

    imaging_summary = "Not performed"
    if imaging_output and not imaging_output.get("mock", False):
        pred = imaging_output.get("model_output", {}).get("prediction", "N/A")
        conf = imaging_output.get("model_output", {}).get("confidence", 0)
        triage = imaging_output.get("severity_assessment", {}).get("triage_label", "")
        imaging_summary = f"Chest X-ray: {pred} ({conf:.0%} confidence, {triage})"

    drug_safety_summary = "No drug safety alerts"
    if drug_safety_output:
        status = drug_safety_output.get("safety_status", "SAFE")
        flagged = drug_safety_output.get("flagged_medications", [])
        if flagged:
            drug_safety_summary = f"UNSAFE — {', '.join(flagged[:3])} flagged"
        elif status == "SAFE":
            approved = drug_safety_output.get("approved_medications", [])
            drug_safety_summary = f"SAFE — {', '.join(approved[:3]) or 'medications reviewed'}"

    final_diagnosis = consensus_output.get("final_diagnosis", "Diagnosis pending")
    confidence = consensus_output.get("aggregate_confidence", 0.0)

    treatment_recommendation = "Clinical judgment required"
    if digital_twin_output and not digital_twin_output.get("mock", False):
        rec_id = digital_twin_output.get("simulation_summary", {}).get("recommended_option", "")
        scenarios = digital_twin_output.get("scenarios", [])
        rec_scenario = next((s for s in scenarios if s.get("option_id") == rec_id), None)
        if rec_scenario:
            treatment_recommendation = (
                f"Option {rec_id}: {rec_scenario.get('label', '')}. "
                f"Predicted 7-day recovery: {rec_scenario.get('predictions', {}).get('recovery_probability_7d', 0):.0%}"
            )

    mortality_risk = 0.0
    readmission_risk = 0.0
    if digital_twin_output and not digital_twin_output.get("mock", False):
        baseline = digital_twin_output.get("simulation_summary", {}).get("baseline_risks", {})
        mortality_risk = baseline.get("mortality_30d", 0.0)
        readmission_risk = baseline.get("readmission_30d", 0.0)

    # Try LLM
    if api_key:
        try:
            llm = ChatGoogleGenerativeAI(model="models/gemini-2.5-flash", temperature=0.2)
            prompt = ChatPromptTemplate.from_messages([
                ("system", SOAP_SYSTEM),
                ("human", SOAP_USER),
            ])
            chain = prompt | llm | JsonOutputParser()

            result = chain.invoke({
                "age": age, "gender": gender,
                "chief_complaint": chief_complaint,
                "conditions": conditions,
                "medications": medications,
                "allergies": allergies,
                "abnormal_labs": abnormal_labs,
                "imaging_summary": imaging_summary,
                "drug_safety_summary": drug_safety_summary,
                "final_diagnosis": final_diagnosis,
                "confidence": confidence,
                "treatment_recommendation": treatment_recommendation,
                "mortality_risk": mortality_risk,
                "readmission_risk": readmission_risk,
            })

            # Always append medical disclaimer to assessment — never LLM-dependent
            result["assessment"] = result.get("assessment", "") + MEDICAL_DISCLAIMER
            return result

        except Exception as e:
            print(f"  ⚠️  SOAP LLM failed: {e} — using template fallback")

    # Rule-based fallback
    return {
        "subjective": (
            f"{age}y {gender} presenting with {chief_complaint}. "
            f"PMH: {conditions}. Allergies: {allergies}."
        ),
        "objective": (
            f"Medications: {medications}. "
            f"Abnormal labs: {abnormal_labs}. "
            f"Imaging: {imaging_summary}. "
            f"Drug safety: {drug_safety_summary}."
        ),
        "assessment": (
            f"{final_diagnosis} — confidence {confidence:.0%}. "
            f"{drug_safety_summary}. "
            f"Baseline 30d mortality: {mortality_risk:.0%}."
            + MEDICAL_DISCLAIMER
        ),
        "plan": [
            treatment_recommendation,
            "Clinical review required",
            "Monitor vital signs",
            "Follow up as clinically indicated",
        ],
        "clinical_summary_one_liner": (
            f"{age}y {gender} — {final_diagnosis} — {drug_safety_summary}"
        ),
    }